# Codecov Configuration for DIGIPIN-Py
# Learn more: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "python/tests/"
  - "python/examples/"
  - "python/benchmarks/"
  - "javascript/"
  - "docs/"
  - "setup.py"
  - "**/test_*.py"
  - "**/__pycache__"

flags:
  unittests:
    paths:
      - python/src/digipin/
    carryforward: true
